name: Run tests

on:
  workflow_dispatch:

jobs:
  run-unit-tests:
    name: Run tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: SubstringCounter.Tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8
      - run: dotnet test
        env:
          CI: true
